### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (4681 > 1024). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by SumanthSrungavarapu** [SKRohit/Generating_Text_Summary_With_GPT2#11]
In the blog you said you only chose those files which had a maximum 512 and 1024 tokens after tokenizing, can you tell what part of code did this. because after executing this 
 [$ python max_article_sizes.py path/to/cnn_or_dailymail/tokenized/articles]
A pickle file is created in CNN or DM folder going through all the files
after executing this 
$ python prepare_data.py [path/to/pickle_file/of/articles/sizes/created/using/above/command]
in the CNN folder a folder names gpt2_1024 data which has around 59,2888 json files.
This doubt came to me because in the blog you said you chose around 1500 items but the json files created here are a lot larger than that. and during execution also after some files are written it said this 
[Token indices sequence length is longer than the specified maximum sequence length for this model (4681 > 1024). Running this sequence through the model will result in indexing errors]
Could you please help me with this and tell if i have made any mistake.
Also i am getting some file not found errors while executing the second command (prepare_data.py) and if i copied the cnn_stories_tokenized in to the CNN folder its resolved

**Comment by SKRohit** [comment]
Hi, 
I am busy at work, so couldn't help with all the issues you are facing but in this particular case 

> [Token indices sequence length is longer than the specified maximum sequence length for this model (4681 > 1024). Running this sequence through the model will result in indexing errors]

model is being trained on the first 1024 tokens of that file only (and total no of tokens in that file is 4681). 

Also, I had filtered out txt files that had 1024 and 512 tokens respectively and only used them in training. You will have to write that code on your own, I don't think it is in the repo.
