### ISSUE TITLE
Where is model_file

### ISSUE THREAD

**Issue by SumanthSrungavarapu** [SKRohit/Generating_Text_Summary_With_GPT2#12]
Will we get the model file after training, its taking very long to train on my normal laptop. Can you provide these files so we can skip this part. or suggest any free platforms,
I am trying to do this on google collab but its taking too much time to clone the repository because of the dataset i think, do you have a way do this?

**Comment by SKRohit** [comment]
Here is the model and most probably the data file I used for training https://drive.google.com/file/d/1fmff72Z-9CvpHs2wwTBZJZYTKvbOxebk/view?usp=sharing  and https://drive.google.com/file/d/1fmff72Z-9CvpHs2wwTBZJZYTKvbOxebk/view?usp=sharing. You can try them and see if they work as expected else you will have to train yourself. It has been some time I worked on this project so couldn't find all the data and models I used.

**Comment by SKRohit** [comment]
resolved

**Comment by SumanthSrungavarapu** [comment]
very sorry to disturb you , but i you shared only the data link twice.

**Comment by SumanthSrungavarapu** [comment]
> resolved

> Here is the model and most probably the data file I used for training https://drive.google.com/file/d/1fmff72Z-9CvpHs2wwTBZJZYTKvbOxebk/view?usp=sharing and https://drive.google.com/file/d/1fmff72Z-9CvpHs2wwTBZJZYTKvbOxebk/view?usp=sharing. You can try them and see if they work as expected else you will have to train yourself. It has been some time I worked on this project so couldn't find all the data and models I used.


very sorry to disturb you , but  you shared only the data link twice.
please provide the model file also, thank you
