### ISSUE TITLE
max_articles_size : expected 2 got 1

### ISSUE THREAD

**Issue by AIDRI** [SKRohit/Generating_Text_Summary_With_GPT2#2]
Hey, 
I tested your script to prepare the dataset in order to make my abstract summarizer. I would like to point out that a bug may appear in max_articles_size. Indeed, when you want to list the files in the cnn dataset, zip(os.listdir(file_name)) doesn't work. So we have to use enumerate(os.listdir(file_name)), which allows us to have the i + the name of the file !

**Comment by SKRohit** [comment]
Resolved.
