### ISSUE TITLE
The `generate_sample` miss `model` argument ?

### ISSUE THREAD

**Issue by realliyifei** [SKRohit/Generating_Text_Summary_With_GPT2#6]
It seems that the second `generate_sample` miss `model` argument in `train_gpt_2_summarizer` notebook and python file.

![image](https://user-images.githubusercontent.com/32441766/145128432-351fc5b3-1d46-4d6d-a038-3ecb2d6bd86a.png)

**Comment by hoangthangta** [comment]
I found the same error, I add "model" there:

`generate_sample(valid_dataset, tokenizer, model, num=2, eval_step=False, device=args.device)`

**Comment by realliyifei** [comment]
yes I figured it out later, thanks for reminder

**Comment by SKRohit** [comment]
thank you guys for pointing out these mistakes, I will fix them soon. Currently been busy with some other work.
